# Análise de Sentimento
Este notebook aplica o módulo `sentiment_analyzer` na base de comentários do arquivo `NPS.xlsx`.

In [1]:
import pandas as pd
from sentiment_analyzer import get_sentiment

In [2]:
# Carregar a base de dados
df = pd.read_excel('NPS.xlsx', keep_default_na=False)
df.head(3)

,Response_ID,Client,Segment,Region,Product,Score (0-10),Survey_Date,Comment,Polarity,Sentiment,Dominant_Topic
0,1,Client_32,Enterprise,NA,Product C,0,2025-11-24,"Performance has degraded over time, especially...",0.000000,Neutral,"Tópico 2: performance, time, usage, especially"
1,2,Client_12,Mid-Market,APAC,Product A,10,2025-02-22,"Decent performance, but there is room for impr...",0.166667,Positive,"Tópico 2: performance, time, usage, especially"
2,3,Client_65,Mid-Market,LATAM,Product C,7,2025-01-16,"Support team is proactive and knowledgeable, i...",0.333333,Positive,"Tópico 3: experience, support, overall, issues"

In [3]:
# Aplicar a análise de sentimento na coluna 'Comment'
# Como get_sentiment retorna uma tupla (polaridade, classificação), vamos desempacotar o resultado em duas colunas.
df[['Polarity', 'Sentiment']] = df['Comment'].apply(lambda x: pd.Series(get_sentiment(str(x))))

In [4]:
# Visualizar as primeiras linhas atualizadas e o resumo dos sentimentos
display(df.head())
print('\nDistribuição dos Sentimentos:')
print(df['Sentiment'].value_counts())

,Response_ID,Client,Segment,Region,Product,Score (0-10),Survey_Date,Comment,Polarity,Sentiment,Dominant_Topic
0,1,Client_32,Enterprise,NA,Product C,0,2025-11-24,"Performance has degraded over time, especially...",0.000000,Neutral,"Tópico 2: performance, time, usage, especially"
1,2,Client_12,Mid-Market,APAC,Product A,10,2025-02-22,"Decent performance, but there is room for impr...",0.166667,Positive,"Tópico 2: performance, time, usage, especially"
2,3,Client_65,Mid-Market,LATAM,Product C,7,2025-01-16,"Support team is proactive and knowledgeable, i...",0.333333,Positive,"Tópico 3: experience, support, overall, issues"
3,4,Client_54,Enterprise,APAC,Product C,10,2025-04-12,"Decent performance, but there is room for impr...",0.166667,Positive,"Tópico 2: performance, time, usage, especially"
4,5,Client_98,Enterprise,APAC,Product B,8,2025-05-23,The product meets expectations but could impro...,0.000000,Neutral,"Tópico 2: performance, time, usage, especially"

Distribuição dos Sentimentos:
Sentiment
Neutral     473
Positive    468
Negative     59
Name: count, dtype: int64